version: "3"
services:
  myapp:
    image: myapp
    build:
      context: ./app
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:80
    volumes:
      - myapp:/app
    ## we wait for the MySQL container to be up and running
    ## then we run the migration
    ## and finally we start apache
    entrypoint: sh -c "sleep 30 && php /app/artisan migrate && apache2-foreground"

  queue:
    image: myapp
    depends_on:
      - myapp
    volumes:
      - myapp:/app
    ## for the queue worker, we use the same image, but run 
    ## artisan queue:work
    entrypoint: php /app/artisan queue:work --verbose --tries=3 --timeout=60

  scheduler:
    image: myapp
    depends_on:
      - myapp
    ## for the scheduler we use an infinite while loop
    entrypoint: sh -c "while true; do php /app/artisan schedule:run --verbose & sleep 60; done"

  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp

volumes:
  myapp:
    driver: "local"
  redis:
    driver: "local"
  mysql:
    driver: "local"